// Hex terrain map
// Keys: hex label (e.g. "Q7"), values: array of terrain types
export const hexMap = {
  // Row 0
  '04': ['forest'], '05': ['forest'], '06': ['forest'], '07': ['forest'],
  '011': ['forest'], '012': ['forest'], '013': ['forest'], '014': ['forest'],
  A5: ['dirtRoad'], A6: ['dirtRoad'],
  B5: ['dirtRoad'], C5: ['dirtRoad'], D4: ['dirtRoad', 'orchard'], E4: ['dirtRoad', 'orchard'],
  F3: ['dirtRoad', 'orchard'], G3: ['dirtRoad'], H2: ['dirtRoad'], I2: ['dirtRoad'], I1: ['dirtRoad'],
  J1: ['dirtRoad'], K2: ['dirtRoad'], L1: ['dirtRoad'], M2: ['dirtRoad'],
  N2: ['dirtRoad'], O2: ['dirtRoad'], P1: ['dirtRoad'], Q1: ['dirtRoad'],
  Y1: ['dirtRoad'], Y2: ['dirtRoad'], Y3: ['dirtRoad'],
  Z2: ['orchard'], AA2: ['orchard'],
  CC3: ['orchard', 'hill'], CC4: ['orchard', 'hill'], FF8: ['orchard'],
  X3: ['dirtRoad', 'orchard'], W4: ['dirtRoad', 'orchard'],
  V4: ['dirtRoad', 'orchard'], U5: ['dirtRoad', 'orchard'],
  I10: ['dirtRoad'], I11: ['dirtRoad'],
  Y10: ['dirtRoad'], Y11: ['dirtRoad'], Y12: ['dirtRoad'],
  Z12: ['dirtRoad'], AA13: ['dirtRoad'], BB13: ['dirtRoad'],
  CC14: ['dirtRoad', 'forest'], DD14: ['dirtRoad', 'forest'], EE15: ['dirtRoad', 'forest'],
  FF15: ['dirtRoad'], GG15: ['dirtRoad'], GG16: ['dirtRoad'],
  FF25: ['dirtRoad'], GG25: ['dirtRoad'], GG26: ['dirtRoad'],
  A25: ['dirtRoad'], A26: ['dirtRoad'],
  B25: ['dirtRoad'],
  C23: ['dirtRoad'], C24: ['dirtRoad'],
  D22: ['dirtRoad'],
  E22: ['dirtRoad'],
  F21: ['dirtRoad'],
  G22: ['dirtRoad'],
  H21: ['dirtRoad'],
  I21: ['dirtRoad'], I30: ['dirtRoad'],
  J29: ['dirtRoad'], J30: ['forest'],
  K22: ['dirtRoad'],
  L22: ['dirtRoad'], L26: ['dirtRoad'], L27: ['dirtRoad'], L28: ['dirtRoad'], L29: ['dirtRoad'],
  M23: ['dirtRoad'], M26: ['dirtRoad'],
  N22: ['dirtRoad'], N23: ['dirtRoad'], N24: ['dirtRoad'], N25: ['dirtRoad'],
  O22: ['dirtRoad'], O25: ['dirtRoad'],
  P21: ['dirtRoad'], P24: ['dirtRoad'],
  Q24: ['dirtRoad'], Q30: ['dirtRoad'], R23: ['dirtRoad'], S23: ['dirtRoad'], T22: ['dirtRoad'], U23: ['dirtRoad'],
  Z26: ['dirtRoad'], Z27: ['dirtRoad'],
  Y28: ['dirtRoad'], Y29: ['dirtRoad'], Y30: ['dirtRoad'],
  AA26: ['dirtRoad'], BB25: ['dirtRoad'], CC26: ['dirtRoad'], DD26: ['dirtRoad'],
  Q18: ['dirtRoad'], Q19: ['dirtRoad'], Q20: ['dirtRoad'], Q21: ['dirtRoad'],
  R17: ['dirtRoad'], R21: ['crestLine'], R22: ['crestLine'],
  S21: ['crestLine'], S22: ['crestLine'], S18: ['dirtRoad'], T18: ['dirtRoad'], U18: ['dirtRoad'],
  V17: ['dirtRoad'], W18: ['dirtRoad'], X18: ['dirtRoad'],
  Y19: ['dirtRoad'], Y20: ['dirtRoad'], Y21: ['dirtRoad'], Y22: ['dirtRoad'],
  X22: ['dirtRoad'], W23: ['dirtRoad'], V23: ['dirtRoad'], W24: ['dirtRoad'],
  X24: ['dirtRoad'], Y25: ['dirtRoad'], Z25: ['dirtRoad'],
  J9: ['dirtRoad'], K9: ['dirtRoad'], L8: ['dirtRoad'], M8: ['dirtRoad'], N8: ['dirtRoad'], O9: ['dirtRoad'], P9: ['dirtRoad'],
  T5: ['dirtRoad'], S6: ['dirtRoad'], R6: ['dirtRoad'],
  Q7: ['dirtRoad'], Q8: ['dirtRoad'], Q9: ['dirtRoad'], Q10: ['dirtRoad'],
  Y4: ['dirtRoad'], Z4: ['dirtRoad'],
  AA5: ['dirtRoad', 'hill', 'crestLine'],
  BB5: ['dirtRoad', 'hill'], CC6: ['dirtRoad', 'hill'],
  DD5: ['dirtRoad', 'hill'], EE5: ['dirtRoad', 'hill'],
  FF5: ['dirtRoad', 'hill', 'crestLine'],
  GG5: ['dirtRoad'], GG6: ['dirtRoad'],
  // Hill group 1
  F8: ['crestLine'], G7: ['crestLine'], G8: ['crestLine'], G9: ['crestLine'],
  H6: ['crestLine'], H7: ['crestLine'], I7: ['crestLine'], I8: ['crestLine'],
  J7: ['crestLine'], J8: ['crestLine'], K8: ['crestLine'],
  // Hill group 2
  B2: ['crestLine'], B3: ['crestLine'], B4: ['crestLine'], C2: ['crestLine'],
  C4: ['crestLine'], D2: ['crestLine'], D3: ['crestLine'], E2: ['crestLine'],
  E3: ['crestLine'], F1: ['crestLine'], F2: ['crestLine'],
  // Hill group 3
  G4: ['crestLine'], H3: ['crestLine'], I4: ['crestLine'], J3: ['crestLine'], J4: ['hill'],
  K4: ['crestLine'], L3: ['crestLine'], L4: ['crestLine'], K5: ['crestLine'],
  K6: ['crestLine'], J5: ['crestLine'], I5: ['crestLine'], H4: ['crestLine'], G5: ['crestLine'],
  // Hill group 4
  AA9: ['crestLine', 'forest'], Z8: ['crestLine'], AA8: ['crestLine'],
  BB7: ['crestLine'], BB6: ['crestLine'], AA6: ['crestLine'],
  // Hill group 5
  BB9: ['crestLine', 'forest'], CC10: ['crestLine', 'forest'], DD9: ['crestLine'], DD8: ['crestLine', 'forest'],
  // Hill group 6
  DD4: ['hill'], DD7: ['crestLine', 'forest'], DD6: ['crestLine'], EE6: ['crestLine'],
  FF4: ['crestLine'], EE4: ['crestLine'], DD3: ['crestLine'], DD2: ['crestLine'],
  EE2: ['crestLine'], FF1: ['crestLine'], DD1: ['crestLine'], CC2: ['crestLine'],
  BB2: ['crestLine'], AA3: ['crestLine'], AA4: ['crestLine'], 
  // Paved Road
  A15: ['pavedRoad'], A16: ['pavedRoad'],
  B15: ['pavedRoad'],
  C15: ['pavedRoad'], C16: ['pavedRoad'],
  D14: ['pavedRoad'], D16: ['pavedRoad'],
  E14: ['pavedRoad'], E17: ['pavedRoad'],
  F13: ['pavedRoad'], F17: ['pavedRoad'],
  G13: ['pavedRoad'], G17: ['pavedRoad'], G18: ['pavedRoad'],
  H12: ['pavedRoad'], H16: ['pavedRoad'], H18: ['pavedRoad'],
  I12: ['pavedRoad'], I16: ['pavedRoad'], I19: ['pavedRoad'], I20: ['pavedRoad'],
  J12: ['pavedRoad'], J13: ['pavedRoad'], J14: ['pavedRoad'],
  K13: ['pavedRoad'], K16: ['pavedRoad'], K18: ['pavedRoad', 'orchard'],
  L12: ['pavedRoad'], L16: ['pavedRoad'], L17: ['pavedRoad'],
  M12: ['pavedRoad'], M16: ['pavedRoad', 'orchard'], M18: ['pavedRoad'],
  N12: ['pavedRoad'], N15: ['pavedRoad', 'orchard'], N18: ['pavedRoad'],
  O12: ['pavedRoad'], O15: ['pavedRoad', 'orchard'], O19: ['pavedRoad'],
  // Forest
  A4: ['forest'], A7: ['forest'], A14: ['forest'], A17: ['forest'], A24: ['forest'], A27: ['forest'],
  B6: ['forest'], B7: ['forest'], B8: ['forest'], B17: ['orchard'],
  C7: ['forest'], C8: ['forest'], C11: ['forest'], C12: ['forest'], C13: ['forest'], C17: ['orchard'], C25: ['forest', 'dirtRoad'], C26: ['forest'],
  D6: ['forest'], D11: ['forest'], D24: ['forest'], D25: ['forest'],
  E7: ['forest'], E8: ['forest'], E15: ['orchard', 'crestLine'], E16: ['crestLine', 'woodenBuilding'], E18: ['orchard', 'crestLine'], E20: ['crestLine'],
  F14: ['crestLine', 'woodenBuilding'], F15: ['orchard', 'hill'], F16: ['crestLine'], F18: ['crestLine'], F19: ['crestLine'],
  G14: ['crestLine'], G15: ['orchard', 'hill'], G16: ['crestLine', 'woodenBuilding'], G20: ['crestLine'],
  H13: ['crestLine', 'woodenBuilding'], H14: ['crestLine'], H15: ['crestLine', 'woodenBuilding'], H19: ['crestLine'],
  C19: ['crestLine'], C20: ['crestLine'], E19: ['hill'],
  D15: ['crestLine'], D18: ['crestLine'], D19: ['crestLine'],
  H10: ['forest'], H20: ['forest'], H30: ['forest'],
  J10: ['forest'], J15: ['orchard', 'pavedRoad'], J16: ['orchard', 'pavedRoad'], J17: ['orchard', 'pavedRoad'], J18: ['orchard', 'pavedRoad'], J20: ['forest'], J21: ['forest', 'dirtRoad'],
  K29: ['forest'], K30: ['forest', 'dirtRoad'],
  L10: ['forest'], L20: ['forest'], L30: ['forest'],
  N10: ['forest'], N11: ['forest'], N20: ['forest'], N30: ['forest'],
  P11: ['pavedRoad'], P14: ['orchard', 'pavedRoad'], P18: ['pavedRoad'],
  Q11: ['pavedRoad'], Q12: ['orchard'], Q13: ['orchard'], Q14: ['orchard', 'pavedRoad'],
  R1: ['forest'], R2: ['forest'], R7: ['forest'], R8: ['forest'], R9: ['forest'],
  S2: ['forest'], S3: ['forest'], S7: ['forest'], S8: ['forest'], S9: ['forest'], S10: ['forest'], S13: ['forest'],
  T1: ['forest'], T2: ['forest'], T7: ['forest'], T10: ['forest'], T12: ['forest'], T13: ['forest'], T14: ['forest'], T20: ['forest'], T21: ['orchard'], T30: ['forest'],
  U1: ['forest'], U2: ['forest'], U8: ['forest'], U13: ['forest'], U14: ['forest'], U15: ['forest'], U22: ['orchard'],
  V1: ['forest'], V10: ['forest'], V14: ['forest'], V20: ['forest'], V21: ['orchard'], V22: ['orchard'], V30: ['forest'],
  W28: ['forest'],
  X10: ['forest'], X14: ['forest'], X15: ['forest'], X16: ['forest'], X20: ['forest'], X30: ['forest'],
  Y14: ['forest'], Y15: ['forest'], Y16: ['forest'], Y17: ['forest'], Y18: ['forest'],
  Z10: ['forest'], Z11: ['forest'], Z15: ['forest'], Z16: ['forest'], Z18: ['forest'], Z20: ['forest'], Z28: ['forest'], Z30: ['forest'],
  AA10: ['forest'], AA11: ['forest'], AA12: ['forest'], AA17: ['forest'], AA19: ['forest'], AA21: ['forest'],
  BB3: ['hill'], BB4: ['hill'], BB8: ['forest', 'hill'], BB11: ['forest'], BB14: ['forest'], BB19: ['forest'], BB21: ['forest'],
  CC5: ['hill'], CC7: ['forest', 'hill'], CC8: ['forest', 'hill'], CC9: ['forest', 'hill'], CC11: ['forest'], CC12: ['forest'], CC13: ['forest'], CC14: ['forest'], CC15: ['forest'], CC19: ['forest'],
  DD11: ['forest'], DD12: ['forest'], DD13: ['forest'], DD15: ['forest'], DD19: ['forest'],
  EE13: ['forest'], EE14: ['forest'], EE19: ['forest'], EE26: ['forest', 'dirtRoad'],
  FF22: ['forest'], FF26: ['forest'],
  GG4: ['forest'], GG7: ['forest'], GG14: ['forest'], GG17: ['forest'], GG24: ['forest'], GG27: ['forest'],
  // Wooden buildings
  D17: ['woodenBuilding'],
  F7: ['woodenBuilding'], F12: ['woodenBuilding'],
  G12: ['woodenBuilding'], G19: ['woodenBuilding'],
  H11: ['woodenBuilding'],
  I22: ['woodenBuilding'],
  K10: ['woodenBuilding'],
  L7: ['woodenBuilding'], L9: ['woodenBuilding'],
  M7: ['woodenBuilding'],
  N9: ['woodenBuilding'],
  O11: ['woodenBuilding'], O23: ['woodenBuilding'], O24: ['woodenBuilding'],
  P7: ['woodenBuilding'], P15: ['woodenBuilding'], P17: ['woodenBuilding'], P23: ['woodenBuilding'], P29: ['woodenBuilding'],
  R11: ['woodenBuilding'], R13: ['woodenBuilding'],
  V18: ['woodenBuilding'],
  X23: ['woodenBuilding'],
  Y13: ['woodenBuilding'], Y23: ['woodenBuilding'],
  Z1: ['woodenBuilding'],
  AA27: ['woodenBuilding'],
  FF16: ['woodenBuilding'],
  // Stone buildings
  H17: ['stoneBuilding'],
  I13: ['stoneBuilding'], I14: ['stoneBuilding'], I15: ['stoneBuilding'], I17: ['stoneBuilding'], I18: ['stoneBuilding'],
  J11: ['stoneBuilding'],
  K12: ['stoneBuilding'], K14: ['stoneBuilding'], K15: ['stoneBuilding'], K17: ['stoneBuilding'],
  L13: ['stoneBuilding'], L15: ['stoneBuilding'], L18: ['stoneBuilding'],
  M13: ['stoneBuilding'], M15: ['stoneBuilding'], M17: ['stoneBuilding'], M19: ['stoneBuilding'],
  N13: ['stoneBuilding'], N14: ['stoneBuilding'], N16: ['stoneBuilding'], N17: ['stoneBuilding'],
  O18: ['stoneBuilding'],
  P12: ['stoneBuilding'], P13: ['stoneBuilding'],
  // Brush
  C3: ['brush', 'hill'], D2: ['brush'], D12: ['brush'], E11: ['brush'], E12: ['brush'],
  G1: ['brush'], G2: ['brush'], G30: ['brush'], H1: ['brush'], H28: ['brush'],
  H29: ['brush'], I29: ['brush'], V7: ['brush'], V9: ['brush'], W8: ['brush'],
  W9: ['brush'], X8: ['brush'], Y8: ['brush'], BB17: ['brush'], BB18: ['brush'],
  CC18: ['brush'], CC20: ['brush'], DD16: ['brush'], DD17: ['brush'], DD18: ['brush'],
};
